flaskberry/views/system.py
# -*- coding: utf-8 -*-
import os
import subprocess
import psutil
from datetime import datetime
from flask import Blueprint, render_template, redirect, url_for, flash
from flask.ext.babel import gettext

mod = Blueprint('system', __name__)

@mod.route('/')
def index():
    uptime = datetime.now() - datetime.fromtimestamp(psutil.get_boot_time())
    return render_template('system/system.html',
            uptime = str(uptime).split('.')[0],
            load = os.getloadavg(),
            net = psutil.net_io_counters(),
            memory = psutil.virtual_memory(),
            swap = psutil.swap_memory(),
        )

@mod.route('/shutdown')
def shutdown():
    flash(gettext("Shutting down.<br>When the LEDs on the board stop flashing, \
        it should be safe to unplug your Raspberry Pi."))
    subprocess.call(["sudo", "halt"])
    return redirect(url_for('system.index'))

@mod.route('/reboot')
def reboot():
    flash(gettext("Rebooting... please wait.<br>\
        This will take approx. one minute."))
    subprocess.call(["sudo", "reboot"])
    return redirect(url_for('system.index'))

flaskberry/templates/system/system.html
{% extends "base.html" %}

{% block header %}
<script type="text/javascript">
var refreshTarget = "#info"
</script>
<script type="text/javascript" src="{{ url_for("static", filename="refresh.js") }}"></script>
{% endblock %}

{% block contents %}

<h2>{{ _('System') }}</h2>
<p>
    <a class="btn btn-danger btn-lg" href="{{ url_for('system.shutdown') }}">
        <span class="glyphicon glyphicon-off"></span>
        {{ _('Shutdown') }}
    </a>
    <a class="btn btn-danger btn-lg" href="{{ url_for('system.reboot') }}">
        <span class="glyphicon glyphicon-refresh"></span>
        {{ _('Reboot') }}
    </a>
</p>
<h3>{{ _('System Information') }}</h3>
<p id="info">
    {{ _('Uptime: %(uptime)s', uptime = uptime) }}<br>
    <span title="{{ _('1 min, 5 min, 15 min') }}">
        {% set loads = load|join(", ") %}
        {{ _('Load Average: %(loads)s', loads = loads) }}
    </span><br>
    {% set recv, sent = (net.bytes_recv|filesizeformat, net.bytes_sent|filesizeformat) %}
    {{ _('Network: %(sent)s sent, %(recv)s received', sent = sent, recv = recv) }}<br>
    {% set used, total = ( (memory.total - memory.available)|filesizeformat,
        memory.total|filesizeformat) %}
    {{ _('Memory: %(used)s of %(total)s used (%(percent)s%%)', used = used, total = total, percent = memory.percent) }}<br>
    {% set used, total = ( (swap.total - swap.free)|filesizeformat,
        swap.total|filesizeformat ) %}
    {{ _('Swap: %(used)s of %(total)s used (%(percent)s%%)', 
        used = used, total = total, percent = swap.percent) }}<br>
</p>
{% endblock %}